### ISSUE TITLE
Cameras with position set will interfere with map view

### ISSUE THREAD

**Issue by louh** [tangrams/tangram-play#246]
Perfectly valid, but rarely used Tangram syntax:

```yaml
cameras:
    camera1:
        type: perspective
        position: [-121.970080, 37.403131, 13]
```

Anytime the editor changes and updates the map, it will reset the map view to this position. We should handle this better
