### ISSUE TITLE
Freezing while editing shader involving premature EOF syntax error

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-play#349]
A shader being inject with a premature end of file sometimes freezes tangram-play for unknown reason.

To test this, add a style with any shader injection point, start a multi line comment `/*` without its enclosing `*/`. The shader injected results in incomplete shader (thus the premature EOF syntax error) and makes tangram-play to freeze.
This consistently happens when editing a shader with multiple lines in it, in order to test, try to inject something like:

```yaml
styles: 
    style0:
        shaders:
            blocks:
                color: |
                    /* vec2 var0;















                    vec2 var1;
```
