### ISSUE TITLE
Add pickers for variables in the `shaders:defines`

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#444]

**Comment by louh** [comment]
@patriciogonzalezvivo Can you describe more what this is about? What are the expected structure and values of `shaders:defines`? What sort of pickers are you envisioning?

**Comment by patriciogonzalezvivo** [comment]
values of `defines` inside `shaders` don't trigger pickers... like the rest of the `shaders:blocks` sections. 
Making more modularize... push the setting of block properties to relay more on the use of `defines`. Ex: http://tangrams.github.io/blocks/#elevation-stripes

Those variables have no widget/picker associated... and as we implement more and more reusable blocks this lack of widget is a problem

**Comment by patriciogonzalezvivo** [comment]
The working pickers for glsl shaders (for floats, vec2s and vec3s) is enought... they just need to be trigger inside defines... that's all...

**Comment by louh** [comment]
OK, noting for future reference: this is what the syntax and tree structure for defines looks like.

```yaml
styles:
    elevation-stripes:
        shaders: 
            defines:
                STRIPES_IN: 0.
                STRIPES_OUT: 13.
                STRIPES_MAX_ZOOM: 13.
                NORMAL_TEXTURE_INDEX: 0
                STRIPES_DIR: vec3(-0.600,-0.420,0.600)
                STRIPES_ALPHA: .5
                STRIPES_SCALE: 2.
                STRIPES_PCT: 1.6
```

taken from: https://github.com/tangrams/blocks/blob/gh-pages/elevation/stripes.yaml#L26-L35

Updating this would involve checking for a `define` address; currently, values are only checked for the GLSL inner mode. Defines are not currently tokenized as GLSL. (We are also refactoring pickers in the React framework, so some of this logic may be slightly different already. Vec3 pickers, for instance, require a little more UI TLC and may be momentarily disabled.) cc @irealva
