### ISSUE TITLE
global.order function breaks syntax highlighting

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-play#449]
![screen shot 2016-07-19 at 10 48 09 am](https://cloud.githubusercontent.com/assets/346914/16954302/629292cc-4d9e-11e6-8f5c-bd5fa99cb81d.png)

**Comment by louh** [comment]
@patriciogonzalezvivo, I've changed the wording - assuming you mean "syntax highlighting" and not other kinds of highlighting (like line highlighting)?

**Comment by louh** [comment]
Can you paste in your YAML file here? Do you have any idea why `global.order` of line 49 breaks syntax highlighting, but not the `global.order` of line 42? I would like to look into this further because it appears something else might be going on, not `global.order` per se.

**Comment by patriciogonzalezvivo** [comment]
yep... from that line to the end all syntax highlighting stop working properly

**Comment by patriciogonzalezvivo** [comment]
```yaml
sources:
    mapzen:
        type: TopoJSON
        url: https://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson?api_key=vector-tiles-P6dkVl4

cameras:
    perspective:
        type: flat

global:
    order_add_9: function () { return (feature.sort_key * 20 + 9); }
    order_add_8: function () { return (feature.sort_key * 20 + 8); }
    order_add_7: function () { return (feature.sort_key * 20 + 7); }
    order_add_6: function () { return (feature.sort_key * 20 + 6); }
    order_add_5: function () { return (feature.sort_key * 20 + 5); }
    order_add_4: function () { return (feature.sort_key * 20 + 4); }
    order_add_3: function () { return (feature.sort_key * 20 + 3); }
    order_add_2: function () { return (feature.sort_key * 20 + 2); }
    order_add_1: function () { return (feature.sort_key * 20 + 1); }
    order: function () { return (feature.sort_key * 20); }
    order_sub_1: function () { return (feature.sort_key * 20 - 1); }
    order_sub_2: function () { return (feature.sort_key * 20 - 2); }
    order_sub_3: function () { return (feature.sort_key * 20 - 3); }
    order_sub_4: function () { return (feature.sort_key * 20 - 4); }
    order_sub_5: function () { return (feature.sort_key * 20 - 5); }
    order_sub_6: function () { return (feature.sort_key * 20 - 6); }
    order_sub_7: function () { return (feature.sort_key * 20 - 7); }
    order_sub_8: function () { return (feature.sort_key * 20 - 8); }
    order_sub_9: function () { return (feature.sort_key * 20 - 9); }

layers:
    earth:
        data: { source: mapzen }
        draw:
            polygons:
                order: global.order
                color: '#555'
    water:
        data: { source: mapzen }
        draw:
            polygons:
                order: global.order
                color: '#333'

    landuse:
        data: { source: mapzen }
        draw:
            polygons:
                order: global.order
                color: '#666'
    roads:
        data: { source: mapzen }
        draw:
            lines:
                order: global.order
                color: '#FFF'
                width: 1px
    buildings:
        data: { source: mapzen }
        draw:
            polygons:
                order: global.order
                color: '#999'


```
